---
cleanup_apps_packages:
  - firefox
  - geary
  - "libreoffice*"
  - rhythmbox
  - remmina
  - thunderbird
  - hexchat
  - warpinator
  - hypnotix
  - totem
  - gnome-maps
  - gnome-weather
  - gnome-clocks
  - gnome-contacts
  - gnome-online-accounts
  - gnome-characters
  - gnome-mahjongg
  - gnome-mines
  - gnome-sudoku

cleanup_apps_flatpaks: []
