---
kubectl_version: "latest"
helm_version: "latest"
k9s_version: "latest"
kind_version: "latest"
aws_cli_version: "latest"
aws_cli_install_dir: "/usr/local/aws-cli"
aws_cli_bin_dir: "/usr/local/bin"
docker_apt_release: ""
docker_mint_ubuntu_release_map:
  "22": "noble"
  "21": "jammy"
  "20": "focal"
